CREATE TABLE CART( -- 장바구니
	CART_PK INT PRIMARY KEY,  -- 장바구니 PK
	ACCOUNT_PK INT,   -- 회원 FK
	ITEM_PK INT,   -- 상품 FK
	CART_COUNT INT,  -- 담은 상품 개수
	CONSTRAINT FK_ACCOUNT_CART FOREIGN KEY (ACCOUNT_PK) REFERENCES ACCOUNT(ACCOUNT_PK),
	CONSTRAINT FK_ITEM_CART FOREIGN KEY (ITEM_PK) REFERENCES ITEM(ITEM_PK)
);


SELECT OWNER, TABLE_NAME
FROM ALL_TABLES
WHERE TABLE_NAME = 'CART';


DROP TABLE CART;
--테이블 드랍

DROP TABLE CART CASCADE CONSTRAINTS;
-- 강제 테이블 드랍

-- 해당 컬럼의 조합은 장바구니 테이블에 하나만 존재하는 규칙
-- 한 회원은 한 장바구니에 한 행만 가질 수 있다.
ALTER TABLE CART
ADD CONSTRAINT UK_CART_ACCOUNT_ITEM
UNIQUE (ACCOUNT_PK, ITEM_PK);

-- 시퀀스
CREATE SEQUENCE CART_SEQ
START WITH 5000
INCREMENT BY 1
NOCACHE;


DROP SEQUENCE CART_SEQ; 

-- 회원 구매시 장바구니 삭제
DELETE FROM CART
WHERE ACCOUNT_PK = ?;

-- 장바구니의 상품 삭제
DELETE FROM CART
WHERE CART_PK = ?;


-- 장바구니 추가(만약 장바구니에 같은 상품이 존재하면 수량 +)
MERGE INTO CART C -- 실제 수정 테이블 
USING (
    SELECT -- 임시 테이블
        ? AS ACCOUNT_PK,
        ? AS ITEM_PK,
        ? AS ADD_COUNT   -- 사용자가 선택한 수량
    FROM DUAL
) S
ON ( -- 같은 회원/상품인지 
    C.ACCOUNT_PK = S.ACCOUNT_PK
AND C.ITEM_PK    = S.ITEM_PK
)
WHEN MATCHED THEN -- 둘다 만족하면 상품 개수만 증가
    UPDATE
    SET C.CART_COUNT = C.CART_COUNT + S.ADD_COUNT
WHEN NOT MATCHED THEN
    INSERT ( -- 장바구니가 존재하지 않으면 생성
        CART_PK,
        ACCOUNT_PK,
        ITEM_PK,
        CART_COUNT
    )
    VALUES (
        CART_SEQ.NEXTVAL,
        S.ACCOUNT_PK,
        S.ITEM_PK,
        S.ADD_COUNT
    );
    

-- 사용자가 장바구니 페이지로 넘어 갈때
SELECT
    C.CART_PK,          -- 장바구니 PK
    C.ITEM_PK,          -- 아이템 PK
    C.CART_COUNT,       -- 아이템 개수
    I.ITEM_NAME,        -- 아이템 이름
    I.ITEM_IMAGE_URL,    -- 아이템 이미지
    (I.ITEM_PRICE * C.CART_COUNT) AS TOTAL_PRICE -- 아이템 총 가격
FROM CART C
JOIN ITEM I
  ON C.ITEM_PK = I.ITEM_PK
WHERE C.ACCOUNT_PK = ?
ORDER BY C.CART_PK DESC;

-- 장바구니에서 상품 수량 변경
UPDATE CART
SET CART_COUNT = ?
WHERE CART_PK = ?;


-- account 8000
INSERT INTO CART (CART_PK, ACCOUNT_PK, ITEM_PK, CART_COUNT)
VALUES (CART_SEQ.NEXTVAL, 8000, 2000, 1);
INSERT INTO CART (CART_PK, ACCOUNT_PK, ITEM_PK, CART_COUNT)
VALUES (CART_SEQ.NEXTVAL, 8000, 2005, 2);

-- account 8001
INSERT INTO CART (CART_PK, ACCOUNT_PK, ITEM_PK, CART_COUNT)
VALUES (CART_SEQ.NEXTVAL, 8001, 2008, 1);
INSERT INTO CART (CART_PK, ACCOUNT_PK, ITEM_PK, CART_COUNT)
VALUES (CART_SEQ.NEXTVAL, 8001, 2013, 1);

-- account 8002
INSERT INTO CART (CART_PK, ACCOUNT_PK, ITEM_PK, CART_COUNT)
VALUES (CART_SEQ.NEXTVAL, 8002, 2001, 3);
INSERT INTO CART (CART_PK, ACCOUNT_PK, ITEM_PK, CART_COUNT)
VALUES (CART_SEQ.NEXTVAL, 8002, 2010, 1);
INSERT INTO CART (CART_PK, ACCOUNT_PK, ITEM_PK, CART_COUNT)
VALUES (CART_SEQ.NEXTVAL, 8002, 2018, 1);

-- account 8003
INSERT INTO CART (CART_PK, ACCOUNT_PK, ITEM_PK, CART_COUNT)
VALUES (CART_SEQ.NEXTVAL, 8003, 2004, 2);
INSERT INTO CART (CART_PK, ACCOUNT_PK, ITEM_PK, CART_COUNT)
VALUES (CART_SEQ.NEXTVAL, 8003, 2016, 1);

-- account 8004
INSERT INTO CART (CART_PK, ACCOUNT_PK, ITEM_PK, CART_COUNT)
VALUES (CART_SEQ.NEXTVAL, 8004, 2006, 1);
INSERT INTO CART (CART_PK, ACCOUNT_PK, ITEM_PK, CART_COUNT)
VALUES (CART_SEQ.NEXTVAL, 8004, 2014, 1);
INSERT INTO CART (CART_PK, ACCOUNT_PK, ITEM_PK, CART_COUNT)
VALUES (CART_SEQ.NEXTVAL, 8004, 2019, 2);

-- account 8005
INSERT INTO CART (CART_PK, ACCOUNT_PK, ITEM_PK, CART_COUNT)
VALUES (CART_SEQ.NEXTVAL, 8005, 2002, 1);
INSERT INTO CART (CART_PK, ACCOUNT_PK, ITEM_PK, CART_COUNT)
VALUES (CART_SEQ.NEXTVAL, 8005, 2012, 1);

  
    