DROP SEQUENCE ACCOUNT_SEQ;
DROP SEQUENCE ADDRESS_SEQ;
DROP SEQUENCE CART_SEQ;
DROP SEQUENCE ITEM_SEQ;
DROP SEQUENCE ORDERS_ITEM_SEQ;
DROP SEQUENCE ORDERS_SEQ;
DROP SEQUENCE REVIEW_SEQ;
DROP SEQUENCE WISHLIST_SEQ;

DROP TABLE WISHLIST;
DROP TABLE CART;
DROP TABLE REVIEW;
DROP TABLE ORDERS_ITEM;
DROP TABLE ORDERS;
DROP TABLE ITEM;
DROP TABLE ADDRESS;
DROP TABLE ACCOUNT;


CREATE TABLE ACCOUNT(
	ACCOUNT_PK INT PRIMARY KEY, 
	ACCOUNT_ID VARCHAR(50),	
	ACCOUNT_PASSWORD VARCHAR(100), 
	ACCOUNT_NAME VARCHAR(50),	
	ACCOUNT_EMAIL VARCHAR(100),
	ACCOUNT_PHONE VARCHAR(11),	
	ACCOUNT_DATE DATE DEFAULT SYSDATE,
	ACCOUNT_ROLE VARCHAR(50) DEFAULT 'ACCOUNT'
);

CREATE TABLE ADDRESS(
	ADDRESS_PK INT PRIMARY KEY,
	ACCOUNT_PK INT, --FK
	ADDRESS_NAME VARCHAR(50),
	ADDRESS_IS_DEFAULT NUMBER(1) DEFAULT 0,
	ADDRESS_POSTAL_CODE VARCHAR(20),
	ADDRESS_LINE1 VARCHAR(100),
	ADDRESS_LINE2 VARCHAR(200),
	CONSTRAINT FK_ACCOUNT_ADDRESS FOREIGN KEY (ACCOUNT_PK) REFERENCES ACCOUNT(ACCOUNT_PK)
);

CREATE TABLE ITEM (  -- 상품 테이블
	ITEM_PK INT PRIMARY KEY, -- PK
	ITEM_NAME VARCHAR(100),    -- 상품명
	ITEM_PRICE INT,          -- 상품 가격
	ITEM_STOCK INT,          -- 상품 재고
	ITEM_DESCRIPTION VARCHAR(3000), -- 상품 설명
	ITEM_IMAGE_URL VARCHAR(255)    -- 상품 이미지 경로
);

CREATE TABLE ORDERS(
	ORDERS_PK INT PRIMARY KEY, -- 주문번호
	ACCOUNT_PK INT,   -- 주문자 FK
	ORDERS_DATE DATE DEFAULT SYSDATE, -- 주문날짜
	ORDERS_STATUS VARCHAR(30) DEFAULT 'READY', -- 주문 현황 
	ADDRESS_NAME VARCHAR(50), -- 배송지 이름
	CONSTRAINT FK_ACCOUNT_ORDERS FOREIGN KEY (ACCOUNT_PK) REFERENCES ACCOUNT(ACCOUNT_PK)
);

CREATE TABLE ORDERS_ITEM ( -- 주문 상세번호
	ORDERS_ITEM_PK INT PRIMARY KEY, -- 주문 상세번호
	ORDERS_PK INT,  -- 주문번호 FK
	ITEM_PK INT, -- 상품번호 FK
	ORDERS_ITEM_QUANTITY INT DEFAULT 0, -- 구매수량
	ORDERS_ITEM_PRICE INT DEFAULT 0, -- 주문시점 가격
	CONSTRAINT FK_ORDERS_ORDERS_ITEM FOREIGN KEY (ORDERS_PK) REFERENCES ORDERS(ORDERS_PK),
	CONSTRAINT FK_ITEM_ORDERS_ITEM FOREIGN KEY (ITEM_PK) REFERENCES ITEM(ITEM_PK)
);

CREATE TABLE REVIEW(
	REVIEW_PK INT PRIMARY KEY,
	ACCOUNT_PK INT, --FK
	ITEM_PK INT, --FK
	REVIEW_TITLE VARCHAR(50),
	REVIEW_CONTENT VARCHAR(2000),
	REVIEW_DATE DATE DEFAULT SYSDATE,
	REVIEW_STAR NUMBER(2) DEFAULT 0,
	CONSTRAINT FK_ACCOUNT_REVIEW FOREIGN KEY (ACCOUNT_PK) REFERENCES ACCOUNT(ACCOUNT_PK),
	CONSTRAINT FK_ITEM_REVIEW FOREIGN KEY (ITEM_PK) REFERENCES ITEM(ITEM_PK)
);

CREATE TABLE WISHLIST(
 	WISHLIST_PK INT PRIMARY KEY,
 	ACCOUNT_PK INT,-- FK
 	ITEM_PK INT,  --FK
 	CONSTRAINT FK_ACCOUNT_WISHLIST FOREIGN KEY (ACCOUNT_PK) REFERENCES ACCOUNT(ACCOUNT_PK),
	CONSTRAINT FK_ITEM_WISHLIST FOREIGN KEY (ITEM_PK) REFERENCES ITEM(ITEM_PK)
);

CREATE TABLE CART( -- 장바구니
	CART_PK INT PRIMARY KEY,  -- 장바구니 PK
	ACCOUNT_PK INT,   -- 회원 FK
	ITEM_PK INT,   -- 상품 FK
	CART_COUNT INT,  -- 담은 상품 개수
	CONSTRAINT FK_ACCOUNT_CART FOREIGN KEY (ACCOUNT_PK) REFERENCES ACCOUNT(ACCOUNT_PK),
	CONSTRAINT FK_ITEM_CART FOREIGN KEY (ITEM_PK) REFERENCES ITEM(ITEM_PK)
);

CREATE SEQUENCE CART_SEQ
START WITH 5000
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE ACCOUNT_SEQ
START WITH 8000
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE ADDRESS_SEQ
START WITH 1000
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE ITEM_SEQ
START WITH 2000
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE ORDERS_SEQ
START WITH 3000
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE ORDERS_ITEM_SEQ
START WITH 4000
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE REVIEW_SEQ
START WITH 6000
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE WISHLIST_SEQ
START WITH 7000
INCREMENT BY 1
NOCYCLE
NOCACHE;

