CREATE TABLE ORDERS_ITEM ( -- 주문 상세번호
	ORDERS_ITEM_PK INT PRIMARY KEY, -- 주문 상세번호
	ORDERS_PK INT,  -- 주문번호 FK
	ITEM_PK INT, -- 상품번호 FK
	ORDERS_ITEM_QUANTITY INT DEFAULT 0, -- 구매수량
	ORDERS_ITEM_PRICE INT DEFAULT 0, -- 주문시점 가격
	CONSTRAINT FK_ORDERS_ORDERS_ITEM FOREIGN KEY (ORDERS_PK) REFERENCES ORDERS(ORDERS_PK),
	CONSTRAINT FK_ITEM_ORDERS_ITEM FOREIGN KEY (ITEM_PK) REFERENCES ITEM(ITEM_PK)
);

-- 테이블 드랍
DROP TABLE ORDERS_ITEM;

-- 테이블 강제 드랍
DROP TABLE ORDERS_ITEM CASCADE CONSTRAINTS;

-- 시퀀스
CREATE SEQUENCE ORDERS_ITEM_SEQ
START WITH 4000
INCREMENT BY 1
NOCACHE;

-- 주문상세 생성
INSERT INTO ORDERS_ITEM (
    ORDERS_ITEM_PK,    -- PK
    ORDERS_PK,         -- 주문내역 PK
    ITEM_PK,           -- 상품 PK
    ORDERS_ITEM_QUANTITY,  -- 수량
    ORDERS_ITEM_PRICE      -- 주문 시점 총 가격
) VALUES (
    ORDERS_ITEM_SEQ.NEXTVAL,
    ?,   --:ordersPk,
    ?,   --:itemPk,
    ?,   -- :quantity,
    ?    --:unitPrice * :quantity
);


-- 주문 상세내역 출력
SELECT 
    OI.ORDERS_ITEM_PK,
    OI.ORDERS_PK,
    I.ITEM_PK,
    I.ITEM_IMAGE_URL,             -- 상품 사진
    I.ITEM_NAME,                  -- 상품명
    OI.ORDERS_ITEM_PRICE,         -- 주문 시점 가격
    OI.ORDERS_ITEM_QUANTITY       -- 주문 수량
FROM ORDERS_ITEM OI
JOIN ITEM I
    ON OI.ITEM_PK = I.ITEM_PK
WHERE OI.ORDERS_PK = ?           -- 조회할 주문 내역 PK
ORDER BY OI.ORDERS_ITEM_PK;

-- 주문내역에 있는 주문 상세내역들 삭제
DELETE FROM ORDERS_ITEM
WHERE ORDERS_PK = ?;

-- 시퀸스
SELECT O.ACCOUNT_PK, OI.ITEM_PK 
FROM ORDERS O INNER JOIN ORDERS_ITEM OI
ON O.ORDERS_PK = OI.ORDERS_PK
ORDER BY O.ACCOUNT_PK ASC;


-- [주문 1] account 8000 / 주소명: '집'
INSERT INTO ORDERS (ORDERS_PK, ACCOUNT_PK, ORDERS_STATUS, ADDRESS_NAME)
VALUES (ORDERS_SEQ.NEXTVAL, 8000, 'READY', '집');

INSERT INTO ORDERS_ITEM (ORDERS_ITEM_PK, ORDERS_PK, ITEM_PK, ORDERS_ITEM_QUANTITY, ORDERS_ITEM_PRICE)
VALUES (ORDERS_ITEM_SEQ.NEXTVAL, ORDERS_SEQ.CURRVAL, 2000, 1, 7500);   -- 유광볼 150mm 실버
INSERT INTO ORDERS_ITEM (ORDERS_ITEM_PK, ORDERS_PK, ITEM_PK, ORDERS_ITEM_QUANTITY, ORDERS_ITEM_PRICE)
VALUES (ORDERS_ITEM_SEQ.NEXTVAL, ORDERS_SEQ.CURRVAL, 2005, 2, 2500);   -- 마_솔방울 트리

-- [주문 2] account 8001 / 주소명: '회사'
INSERT INTO ORDERS (ORDERS_PK, ACCOUNT_PK, ORDERS_STATUS, ADDRESS_NAME)
VALUES (ORDERS_SEQ.NEXTVAL, 8001, 'READY', '회사');

INSERT INTO ORDERS_ITEM (ORDERS_ITEM_PK, ORDERS_PK, ITEM_PK, ORDERS_ITEM_QUANTITY, ORDERS_ITEM_PRICE)
VALUES (ORDERS_ITEM_SEQ.NEXTVAL, ORDERS_SEQ.CURRVAL, 2013, 1, 13900);  -- OP-08 투명볼
INSERT INTO ORDERS_ITEM (ORDERS_ITEM_PK, ORDERS_PK, ITEM_PK, ORDERS_ITEM_QUANTITY, ORDERS_ITEM_PRICE)
VALUES (ORDERS_ITEM_SEQ.NEXTVAL, ORDERS_SEQ.CURRVAL, 2016, 3, 1900);   -- 레드 화이트 아크릴 볼

-- [주문 3] account 8002 / 주소명: '회사'
INSERT INTO ORDERS (ORDERS_PK, ACCOUNT_PK, ORDERS_STATUS, ADDRESS_NAME)
VALUES (ORDERS_SEQ.NEXTVAL, 8002, 'READY', '회사');

INSERT INTO ORDERS_ITEM (ORDERS_ITEM_PK, ORDERS_PK, ITEM_PK, ORDERS_ITEM_QUANTITY, ORDERS_ITEM_PRICE)
VALUES (ORDERS_ITEM_SEQ.NEXTVAL, ORDERS_SEQ.CURRVAL, 2001, 1, 7500);   -- 유광볼 150mm 레드
INSERT INTO ORDERS_ITEM (ORDERS_ITEM_PK, ORDERS_PK, ITEM_PK, ORDERS_ITEM_QUANTITY, ORDERS_ITEM_PRICE)
VALUES (ORDERS_ITEM_SEQ.NEXTVAL, ORDERS_SEQ.CURRVAL, 2009, 2, 1900);   -- 미니 빨간리본 곰돌이

-- [주문 4] account 8002 / 주소명: '자취방'
INSERT INTO ORDERS (ORDERS_PK, ACCOUNT_PK, ORDERS_STATUS, ADDRESS_NAME)
VALUES (ORDERS_SEQ.NEXTVAL, 8002, 'READY', '자취방');

INSERT INTO ORDERS_ITEM (ORDERS_ITEM_PK, ORDERS_PK, ITEM_PK, ORDERS_ITEM_QUANTITY, ORDERS_ITEM_PRICE)
VALUES (ORDERS_ITEM_SEQ.NEXTVAL, ORDERS_SEQ.CURRVAL, 2018, 1, 2500);   -- 리본 오너먼트 레드 벨벳
INSERT INTO ORDERS_ITEM (ORDERS_ITEM_PK, ORDERS_PK, ITEM_PK, ORDERS_ITEM_QUANTITY, ORDERS_ITEM_PRICE)
VALUES (ORDERS_ITEM_SEQ.NEXTVAL, ORDERS_SEQ.CURRVAL, 2019, 2, 2500);   -- 리본 불빛 오너먼트

-- [주문 5] account 8004 / 주소명: '회사'
INSERT INTO ORDERS (ORDERS_PK, ACCOUNT_PK, ORDERS_STATUS, ADDRESS_NAME)
VALUES (ORDERS_SEQ.NEXTVAL, 8004, 'READY', '회사');

INSERT INTO ORDERS_ITEM (ORDERS_ITEM_PK, ORDERS_PK, ITEM_PK, ORDERS_ITEM_QUANTITY, ORDERS_ITEM_PRICE)
VALUES (ORDERS_ITEM_SEQ.NEXTVAL, ORDERS_SEQ.CURRVAL, 2014, 1, 9500);   -- 오렌지 곰돌이 빅벤
INSERT INTO ORDERS_ITEM (ORDERS_ITEM_PK, ORDERS_PK, ITEM_PK, ORDERS_ITEM_QUANTITY, ORDERS_ITEM_PRICE)
VALUES (ORDERS_ITEM_SEQ.NEXTVAL, ORDERS_SEQ.CURRVAL, 2006, 1, 2500);   -- 마_눈사람트리

-- [주문 6] account 8005 / 주소명: '집'
INSERT INTO ORDERS (ORDERS_PK, ACCOUNT_PK, ORDERS_STATUS, ADDRESS_NAME)
VALUES (ORDERS_SEQ.NEXTVAL, 8005, 'READY', '집');

INSERT INTO ORDERS_ITEM (ORDERS_ITEM_PK, ORDERS_PK, ITEM_PK, ORDERS_ITEM_QUANTITY, ORDERS_ITEM_PRICE)
VALUES (ORDERS_ITEM_SEQ.NEXTVAL, ORDERS_SEQ.CURRVAL, 2004, 2, 1900);   -- 우드 버튼장식_별
INSERT INTO ORDERS_ITEM (ORDERS_ITEM_PK, ORDERS_PK, ITEM_PK, ORDERS_ITEM_QUANTITY, ORDERS_ITEM_PRICE)
VALUES (ORDERS_ITEM_SEQ.NEXTVAL, ORDERS_SEQ.CURRVAL, 2013, 1, 13900);  -- OP-08 

SELECT * FROM ORDERS;
SELECT * FROM ORDERS_ITEM;

SELECT O.ACCOUNT_PK, OI.ITEM_PK 
FROM ORDERS O INNER JOIN ORDERS_ITEM OI
ON O.ORDERS_PK = OI.ORDERS_PK
ORDER BY O.ACCOUNT_PK ASC;

