CREATE TABLE ORDERS(
	ORDERS_PK INT PRIMARY KEY, -- 주문번호
	ACCOUNT_PK INT,   -- 주문자 FK
	ORDERS_DATE DATE DEFAULT SYSDATE, -- 주문날짜
	ORDERS_STATUS VARCHAR(30) DEFAULT 'READY', -- 주문 현황 
	ADDRESS_PK INT, -- 배송지 주소(FK)
	CONSTRAINT FK_ACCOUNT_ORDERS FOREIGN KEY (ACCOUNT_PK) REFERENCES ACCOUNT(ACCOUNT_PK),
	CONSTRAINT FK_ADDRESS_ORDERS FOREIGN KEY (ADDRESS_PK) REFERENCES ADDRESS(ADDRESS_PK)
);

select * from orders;

-- 테이블 드랍
DROP TABLE ORDERS;
-- 테이블 강제 드랍
DROP TABLE ORDERS CASCADE CONSTRAINTS;

-- 주문내역 PK 100부터 1씩 자동 증가 시퀀스
CREATE SEQUENCE ORDERS_SEQ
START WITH 3000
INCREMENT BY 1
NOCACHE;


-- 주문내역 샘플 데이터
INSERT INTO ORDERS (ORDERS_PK, ACCOUNT_PK, ORDERS_STATUS, ADDRESS_PK) VALUES (3000, 8000, 'READY', 1000);
INSERT INTO ORDERS (ORDERS_PK, ACCOUNT_PK, ORDERS_STATUS, ADDRESS_PK) VALUES (3001, 8000, 'READY', 1000);
INSERT INTO ORDERS (ORDERS_PK, ACCOUNT_PK, ORDERS_STATUS, ADDRESS_PK) VALUES (3002, 8002, 'DELIVERY', 1002);
INSERT INTO ORDERS (ORDERS_PK, ACCOUNT_PK, ORDERS_STATUS, ADDRESS_PK) VALUES (3003, 8002, 'COMPLETE', 1009);
INSERT INTO ORDERS (ORDERS_PK, ACCOUNT_PK, ORDERS_STATUS, ADDRESS_PK) VALUES (3004, 8003, 'DELIVERY', 1003);
INSERT INTO ORDERS (ORDERS_PK, ACCOUNT_PK, ORDERS_STATUS, ADDRESS_PK) VALUES (3005, 8001, 'READY', 1001);

-- 사용자의 주문내역 전체 보기
SELECT
    O.ORDERS_PK,
    O.ORDERS_DATE,
    O.ORDERS_STATUS,
    -- 대표 상품명 (주문에 포함된 상품 중 가장 첫 번째 상품)
    MIN(I.ITEM_NAME) AS ITEM_NAME,
    -- 총 결제 금액 (당시 가격)
    SUM(OI.ORDERS_ITEM_PRICE * OI.ORDERS_ITEM_QUANTITY) AS TOTAL_PRICE 
FROM ORDERS O
JOIN ORDERS_ITEM OI 
    ON O.ORDERS_PK = OI.ORDERS_PK
JOIN ITEM I
    ON OI.ITEM_PK = I.ITEM_PK
WHERE O.ACCOUNT_PK = ? -- 사용자 pk 받음
GROUP BY
    O.ORDERS_PK,
    O.ORDERS_DATE,
    O.ORDERS_STATUS
ORDER BY O.ORDERS_DATE DESC;

-- 결제시 주문내역 생성
INSERT INTO ORDERS (
    ORDERS_PK,
    ACCOUNT_PK,
    ORDERS_DATE,
    ADDRESS_PK
) VALUES (
    ORDERS_SEQ.NEXTVAL,
    ?,
    SYSDATE,
    ?
);

-- 주문상세 생성을 위한 주문내역 PK 전송
SELECT ORDERS_PK
FROM ORDERS
WHERE ACCOUNT_PK = ?
AND ROWNUM = 1;

-- 회원 탈퇴시 주문내역 삭제
DELETE FROM ORDERS WHERE ACCOUNT_PK = ?;



