CREATE TABLE REVIEW(
	REVIEW_PK INT PRIMARY KEY,
	ACCOUNT_PK INT, --FK
	ITEM_PK INT, --FK
	REVIEW_TITLE VARCHAR(50),
	REVIEW_CONTENT VARCHAR(2000),
	REVIEW_DATE DATE DEFAULT SYSDATE,
	REVIEW_STAR NUMBER(1) DEFAULT 0,

	CONSTRAINT FK_ACCOUNT_REVIEW FOREIGN KEY (ACCOUNT_PK) REFERENCES ACCOUNT(ACCOUNT_PK),
	CONSTRAINT FK_ITEM_REVIEW FOREIGN KEY (ITEM_PK) REFERENCES ITEM(ITEM_PK)
);
--리뷰PK,회원PK,상품PK,리뷰제목,리뷰내용,리뷰날자,리뷰 별점
--FK 연결하고 명시적 선언

DROP TABLE REVIEW;
-- 테이블 드랍
DROP TABLE REVIEW CASCADE CONSTRAINTS;
-- 강제 테이블 드랍



--필요한거
--상품별리뷰
--내가쓴 리뷰 확인
--리뷰작성
--리뷰수정
--리뷰 모두삭제
--리뷰 하나만 삭제

--리뷰PK 자동증가용 시퀀스 사용
CREATE SEQUENCE REVIEW_SEQ
START WITH 6000
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- 시퀀스 삭제
DROP SEQUENCE REVIEW_SEQ;

-- 리뷰작성
INSERT INTO REVIEW (REVIEW_PK, ACCOUNT_PK, ITEM_PK, REVIEW_TITLE, REVIEW_CONTENT, REVIEW_STAR)
VALUES (REVIEW_SEQ.NEXTVAL, 8000, 2000, '반짝임 좋아요', '사진처럼 깔끔하고 반짝임이 예뻐요.', 9);

INSERT INTO REVIEW (REVIEW_PK, ACCOUNT_PK, ITEM_PK, REVIEW_TITLE, REVIEW_CONTENT, REVIEW_STAR)
VALUES (REVIEW_SEQ.NEXTVAL, 8001, 2013, '구성 괜찮음', '수량도 적당하고 트리에 잘 어울립니다.', 8);

INSERT INTO REVIEW (REVIEW_PK, ACCOUNT_PK, ITEM_PK, REVIEW_TITLE, REVIEW_CONTENT, REVIEW_STAR)
VALUES (REVIEW_SEQ.NEXTVAL, 8002, 2001, '색감 선명', '레드 색감이 선명해서 포인트로 좋아요.', 10);

INSERT INTO REVIEW (REVIEW_PK, ACCOUNT_PK, ITEM_PK, REVIEW_TITLE, REVIEW_CONTENT, REVIEW_STAR)
VALUES (REVIEW_SEQ.NEXTVAL, 8004, 2014, '귀여운 편', '디테일 괜찮고 선물용으로도 무난해요.', 7);

INSERT INTO REVIEW (REVIEW_PK, ACCOUNT_PK, ITEM_PK, REVIEW_TITLE, REVIEW_CONTENT, REVIEW_STAR)
VALUES (REVIEW_SEQ.NEXTVAL, 8005, 2004, '가성비 무난', '작지만 장식용으로 쓰기 좋아요.', 6);






-- 샘플 데이터 (2000 상품 리뷰)
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8000, 2000, '좋아요', '상품 5000 사용 후기입니다.', SYSDATE, 5);
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8001, 2000, '무난해요', '전반적으로 만족합니다.', SYSDATE, 4);

-- 샘플 데이터 (2001 상품 리뷰)
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8002, 2001, '추천', '가성비 좋은 상품이에요.', SYSDATE, 5);
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8003, 2001, '보통', '기대보단 평범합니다.', SYSDATE, 3);
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8004, 2001, '만족', '재구매 의사 있어요.', SYSDATE, 4);

-- 샘플 데이터 (2002 상품 리뷰)
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8005, 2002, '만족합니다', '전체적으로 완성도가 높은 상품이에요.', SYSDATE, 5);
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8003, 2002, '무난해요', '특별하진 않지만 사용하기 괜찮습니다.', SYSDATE, 3);
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8001, 2002, '좋아요', '가격 대비 성능이 좋아서 만족해요.', SYSDATE, 4);
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8002, 2002, '아쉬움', '기대했던 부분이 조금 부족했어요.', SYSDATE, 2);
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8004, 2002, '추천', '재구매 의사 있을 만큼 괜찮은 상품입니다.', SYSDATE, 5);
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8001, 2002, '보통', '장단점이 뚜렷한 상품이에요.', SYSDATE, 3);

-- 샘플 데이터 (2003 상품 리뷰)
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8001, 2003, '만족', '배송도 빠르고 좋아요.', SYSDATE, 5);
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8003, 2003, '좋음', '품질이 괜찮네요.', SYSDATE, 4);
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8004, 2003, '보통', '가격 대비 무난.', SYSDATE, 3);

-- 샘플 데이터 (2004 상품 리뷰)
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8002, 2004, '추천', '선물용으로 좋아요.', SYSDATE, 5);
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8000, 2004, '만족', '전체적으로 좋습니다.', SYSDATE, 4);

-- 샘플 데이터 (2005 상품 리뷰)
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8004, 2005, '좋음', '선물용으로 좋아요.', SYSDATE, 5);
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8002, 2005, '만족', '전체적으로 좋습니다.', SYSDATE, 4);

-- 샘플 데이터 (2006 상품 리뷰)
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8002, 2006, '추천', '선물용으로 좋아요.', SYSDATE, 5);
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8001, 2006, '만족', '전체적으로 좋습니다.', SYSDATE, 4);

-- 샘플 데이터 (2007 상품 리뷰)
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8000, 2007, '괜찮아요', '사용하기 편합니다.', SYSDATE, 4);
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8002, 2007, '아쉬움', '조금 부족한 느낌이에요.', SYSDATE, 2);

-- 샘플 데이터 (2008 상품 리뷰)
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8001, 2008, '추천', '가성비 좋은 상품이에요.', SYSDATE, 5);
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8003, 2008, '보통', '기대보단 평범합니다.', SYSDATE, 3);
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8002, 2008, '만족', '재구매 의사 있어요.', SYSDATE, 4);

-- 샘플 데이터 (2009 상품 리뷰)
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8003, 2009, '괜찮아요', '사용하기 편합니다.', SYSDATE, 4);
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8000, 2009, '아쉬움', '조금 부족한 느낌이에요.', SYSDATE, 2);
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8002, 2009, '나쁘지않아요', '사용하기 편합니다.', SYSDATE, 4);
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8001, 2009, '살짝아쉬움', '조금 부족한 느낌이에요.', SYSDATE, 2);

-- 샘플 데이터 (2010 상품 리뷰)
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8000, 20010, '편해요', '사용하기 편합니다.', SYSDATE, 4);
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8002, 20010, '괜찮음', '조금 부족한 느낌이에요.', SYSDATE, 2);
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8001, 20010, '그럭저럭', '사용하기 편합니다.', SYSDATE, 4);
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8004, 20010, '조금아쉬워요', '조금 부족한 느낌이에요.', SYSDATE, 2);

-- 샘플 데이터 (2011 상품 리뷰)
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8005, 2011, '좋아요', '사용하기 편합니다.', SYSDATE, 4);
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8001, 2011, '조금그렇네용', '조금 부족한 느낌이에요.', SYSDATE, 2);

-- 샘플 데이터 (2012 상품 리뷰)
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8004, 2012, '좋음', '선물용으로 좋아요.', SYSDATE, 5);
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8001, 2012, '만족', '전체적으로 좋습니다.', SYSDATE, 4);

-- 샘플 데이터 (2013 상품 리뷰)
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8000, 2013, '만족해요', '상품 5005는 품질이 좋아서 만족합니다.', SYSDATE, 5);
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8001, 2013, '괜찮습니다', '사용하기 무난한 상품이에요.', SYSDATE, 4);
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8002, 2013, '보통이에요', '기대보다는 평범한 느낌입니다.', SYSDATE, 3);
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8003, 2013, '아쉬워요', '디자인은 좋은데 사용성이 조금 아쉽네요.', SYSDATE, 2);
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8004, 2013, '추천합니다', '가격 대비 성능이 좋아서 추천해요.', SYSDATE, 5);

-- 샘플 데이터 (2014 상품 리뷰)
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8005, 2014, '그럭저럭이에요', '기대보다는 평범한 느낌입니다.', SYSDATE, 3);
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8001, 2014, '아쉬워요', '디자인은 좋은데 사용성이 조금 아쉽네요.', SYSDATE, 2);

-- 샘플 데이터 (2015 상품 리뷰)
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8005, 2015, '만족', '배송도 빠르고 좋아요.', SYSDATE, 5);
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8002, 2015, '좋음', '품질이 괜찮네요.', SYSDATE, 4);
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8001, 2015, '보통', '가격 대비 무난.', SYSDATE, 3);

-- 샘플 데이터 (2016 상품 리뷰)
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8001, 2016, '만족합니다', '전체적으로 완성도가 높은 상품이에요.', SYSDATE, 5);
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8004, 2016, '무난해요', '특별하진 않지만 사용하기 괜찮습니다.', SYSDATE, 3);
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8005, 2016, '좋아요', '가격 대비 성능이 좋아서 만족해요.', SYSDATE, 4);
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8003, 2016, '아쉬움', '기대했던 부분이 조금 부족했어요.', SYSDATE, 2);
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8002, 2016, '추천', '재구매 의사 있을 만큼 괜찮은 상품입니다.', SYSDATE, 5);
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8000, 2016, '보통', '장단점이 뚜렷한 상품이에요.', SYSDATE, 3);

-- 샘플 데이터 (2017 상품 리뷰)
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8005, 2017, '괜찮아요', '사용하기 편합니다.', SYSDATE, 4);
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8004, 2017, '아쉬움', '조금 부족한 느낌이에요.', SYSDATE, 2);

-- 샘플 데이터 (2018 상품 리뷰)
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8005, 2018, '그럭저럭이에요', '기대보다는 평범한 느낌입니다.', SYSDATE, 3);
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8001, 2018, '아쉬워요', '디자인은 좋은데 사용성이 조금 아쉽네요.', SYSDATE, 2);

-- 샘플 데이터 (2019 상품 리뷰)
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8001, 2009, '괜찮아요', '사용하기 편합니다.', SYSDATE, 4);
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8003, 2009, '아쉬움', '조금 부족한 느낌이에요.', SYSDATE, 2);
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8005, 2009, '나쁘지않아요', '사용하기 편합니다.', SYSDATE, 4);
INSERT INTO REVIEW VALUES (REVIEW_SEQ.NEXTVAL, 8004, 2009, '살짝아쉬움', '조금 부족한 느낌이에요.', SYSDATE, 2);




--상품별리뷰 -> 페이지네이션 사용
--SELECT 1 ->리뷰PK,아이템PK,리뷰제목,리뷰내용,별점 가져오기
--SELECT 2 ->리뷰테이블 안에 있는 리뷰PK,아이템PK,리뷰제목,리뷰내용,별점 가져오기
--ROW_NUMBER() : 조회된 리뷰 하나하나에 번호 붙이기
--OREDR BY REVIEW_PK DESC
--최신리뷰가 1번이 되도록 설정
--특정 상품의 리뷰만 조회

SELECT 
    REVIEW_PK,
    ITEM_PK,
    REVIEW_TITLE,
    REVIEW_CONTENT,
    REVIEW_STAR
FROM (
    SELECT 
        R.REVIEW_PK,
       	R.ITEM_PK,
        R.REVIEW_TITLE,
        R.REVIEW_CONTENT,
        R.REVIEW_STAR,
        ROW_NUMBER() OVER (
            ORDER BY R.REVIEW_PK DESC
        ) AS RN
    FROM REVIEW R
    WHERE ITEM_PK ='1'
)
WHERE RN BETWEEN 5 AND 5;

--리뷰 존재여부 확인
SELECT COUNT(*)FROM REVIEW 
WHERE ACCOUNT_PK = '2'
  AND ITEM_PK = '1';

--내가쓴 리뷰 확인
SELECT REVIEW_PK,ITEM_PK,ACCOUNT_PK,REVIEW_TITLE,REVIEW_CONTENT,REVIEW_STAR
FROM REVIEW WHERE ACCOUNT_PK = '2';

--상품별 전체 리뷰 개수
SELECT COUNT(*) FROM WHERE ITEM_PK ='1';

--리뷰수정페이지 데이터조회(리뷰수정화면 전용) -> 어카운트 조인필요
--어떤리뷰 수정할건지 내가쓴 리뷰가 맞는지 내이름 화면에 표시하기
SELECT
	R.REVIEW_PK,
	A.ACCOUNT_NAME,
	R.REVIEW_TITLE,
	R.REVIEW_STAR,
	R.REVIEW_CONTENT
FROM REVIEW R
JOIN ACCOUNT A
	ON R.ACCOUNT_PK = A.ACCOUNT_PK
	WHERE R.REVIEW_PK ='3'
	AND R.ACCOUNT_PK = '2';


--상품별 별점 목록
SELECT REVIEW_STAR FROM REVIEW WHERE ITEM_PK ='1';



--리뷰수정
UPDATE REVIEW
SET
    REVIEW_TITLE   = '수정된 제목',
    REVIEW_CONTENT = '수정된 내용',
    REVIEW_STAR    = '4'
WHERE REVIEW_PK = '3'
  AND ACCOUNT_PK = '2'
  AND ITEM_PK='1';

--내가쓴 모든리뷰삭제
DELETE FROM REVIEW WHERE ACCOUNT_PK = '2'; 

--내가쓴리뷰 하나만삭제
DELETE FROM REVIEW
WHERE REVIEW_PK = '3'
AND ACCOUNT_PK = '2';

--확인용
SELECT*FROM REVIEW;


/*



--리뷰작성 인서트 체크용
INSERT INTO ITEM(
	ITEM_PK,ITEM_NAME
)VALUES('1','전구'
);

INSERT INTO ITEM(
	ITEM_PK,ITEM_NAME
)VALUES('2','트리'
);
*/

