CREATE TABLE WISHLIST(
 	WISHLIST_PK INT PRIMARY KEY,
 	ACCOUNT_PK INT,-- FK
 	ITEM_PK INT,  --FK
 	
	CONSTRAINT FK_ACCOUNT_WISHLIST FOREIGN KEY (ACCOUNT_PK) REFERENCES ACCOUNT(ACCOUNT_PK),
	CONSTRAINT FK_ITEM_WISHLIST FOREIGN KEY (ITEM_PK) REFERENCES ITEM(ITEM_PK)
);
--리뷰번호, 회원번호, 상품번호
--FK 연결하고 명시적 선언함

DROP TABLE ORDERS;

DROP TABLE ORDERS CASCADE CONSTRAINTS;
-- 테이블 강제삭제
-- 우리 플젝에 fk너무 많음 테이블 삭제 편리성 위해 만듬



--필요한거
-- 리뷰행 존재시 -> 삭제
-- 행 없으면 -> 좋아요 생성
--좋아요 목록
--좋아요 중복방지

-- 좋아요 PK 시퀀스 생성
CREATE SEQUENCE WISHLIST_SEQ
START WITH 7000
INCREMENT BY 1
NOCYCLE
NOCACHE;

DROP SEQUENCE WISHLIST_SEQ;
-- 시퀀스 삭제


-- 좋아요 존재여부확인 = 중복방지
SELECT WISHLIST_PK FROM WISHLIST
WHERE ACCOUNT_PK = '2'
	AND ITEM_PK = '1';

--결과 있음 ->이미 좋아요누름
--결과 없음 -> 좋아요 안된 상태

--존재하는경우 삭제
DELETE FROM WISHLIST WHERE ACCOUNT_PK = '2'
AND ITEM_PK = '1';

--존재하지 않을 경우 -> 생성
INSERT INTO WISHLIST (WISHLIST_PK,ACCOUNT_PK,ITEM_PK)
VALUES (WISHLIST_SEQ.NEXTVAL,'2','1');

--좋아요 목록
SELECT ACCOUNT_PK,ITEM_PK,WISHLIST_PK FROM WISHLIST
WHERE ACCOUNT_PK = '2';

--좋아요 모두삭제
DELETE FROM WISHLIST WHERE ACCOUNT_PK ='2';


	

--확인용
SELECT*FROM WISHLIST;
	
	


-- 8000
INSERT INTO WISHLIST (WISHLIST_PK, ACCOUNT_PK, ITEM_PK)
VALUES (WISHLIST_SEQ.NEXTVAL, 8000, 2013);
INSERT INTO WISHLIST (WISHLIST_PK, ACCOUNT_PK, ITEM_PK)
VALUES (WISHLIST_SEQ.NEXTVAL, 8000, 2017);

-- 8001
INSERT INTO WISHLIST (WISHLIST_PK, ACCOUNT_PK, ITEM_PK)
VALUES (WISHLIST_SEQ.NEXTVAL, 8001, 2007);

-- 8002
INSERT INTO WISHLIST (WISHLIST_PK, ACCOUNT_PK, ITEM_PK)
VALUES (WISHLIST_SEQ.NEXTVAL, 8002, 2012);
INSERT INTO WISHLIST (WISHLIST_PK, ACCOUNT_PK, ITEM_PK)
VALUES (WISHLIST_SEQ.NEXTVAL, 8002, 2015);

-- 8003
INSERT INTO WISHLIST (WISHLIST_PK, ACCOUNT_PK, ITEM_PK)
VALUES (WISHLIST_SEQ.NEXTVAL, 8003, 2014);

-- 8004
INSERT INTO WISHLIST (WISHLIST_PK, ACCOUNT_PK, ITEM_PK)
VALUES (WISHLIST_SEQ.NEXTVAL, 8004, 2000);
INSERT INTO WISHLIST (WISHLIST_PK, ACCOUNT_PK, ITEM_PK)
VALUES (WISHLIST_SEQ.NEXTVAL, 8004, 2018);

-- 8005
INSERT INTO WISHLIST (WISHLIST_PK, ACCOUNT_PK, ITEM_PK)
VALUES (WISHLIST_SEQ.NEXTVAL, 8005, 2009);
INSERT INTO WISHLIST (WISHLIST_PK, ACCOUNT_PK, ITEM_PK)
VALUES (WISHLIST_SEQ.NEXTVAL, 8005, 2016);